//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iridium.Numerics.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Iridium.Numerics.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 The histogram does not contains the value {0}. 的當地語系化字串。
        /// </summary>
        internal static string ArgumentHistogramContainsNot {
            get {
                return ResourceManager.GetString("ArgumentHistogramContainsNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Value is expected to be between {0} and {1} (including {0} and {1}). 的當地語系化字串。
        /// </summary>
        internal static string ArgumentInIntervalXYInclusive {
            get {
                return ResourceManager.GetString("ArgumentInIntervalXYInclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The matrix indices must not be out of range of the given matrix. 的當地語系化字串。
        /// </summary>
        internal static string ArgumentMatrixIndexOutOfRange {
            get {
                return ResourceManager.GetString("ArgumentMatrixIndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Matrix must not be rank deficient. 的當地語系化字串。
        /// </summary>
        internal static string ArgumentMatrixNotRankDeficient {
            get {
                return ResourceManager.GetString("ArgumentMatrixNotRankDeficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Matrix must not be singular. 的當地語系化字串。
        /// </summary>
        internal static string ArgumentMatrixNotSingular {
            get {
                return ResourceManager.GetString("ArgumentMatrixNotSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Matrix column dimensions must agree. 的當地語系化字串。
        /// </summary>
        internal static string ArgumentMatrixSameColumnDimension {
            get {
                return ResourceManager.GetString("ArgumentMatrixSameColumnDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Matrix dimensions must agree. 的當地語系化字串。
        /// </summary>
        internal static string ArgumentMatrixSameDimensions {
            get {
                return ResourceManager.GetString("ArgumentMatrixSameDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Matrix row dimensions must agree. 的當地語系化字串。
        /// </summary>
        internal static string ArgumentMatrixSameRowDimension {
            get {
                return ResourceManager.GetString("ArgumentMatrixSameRowDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Matrix must have exactly one column. 的當地語系化字串。
        /// </summary>
        internal static string ArgumentMatrixSingleColumn {
            get {
                return ResourceManager.GetString("ArgumentMatrixSingleColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Matrix must have exactly one column and row, thus have only one cell. 的當地語系化字串。
        /// </summary>
        internal static string ArgumentMatrixSingleColumnRow {
            get {
                return ResourceManager.GetString("ArgumentMatrixSingleColumnRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Matrix must have exactly one row. 的當地語系化字串。
        /// </summary>
        internal static string ArgumentMatrixSingleRow {
            get {
                return ResourceManager.GetString("ArgumentMatrixSingleRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Matrix must be square. 的當地語系化字串。
        /// </summary>
        internal static string ArgumentMatrixSquare {
            get {
                return ResourceManager.GetString("ArgumentMatrixSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Matrix must be symmetric. 的當地語系化字串。
        /// </summary>
        internal static string ArgumentMatrixSymmetric {
            get {
                return ResourceManager.GetString("ArgumentMatrixSymmetric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Matrix must be symmetric positive definite. 的當地語系化字串。
        /// </summary>
        internal static string ArgumentMatrixSymmetricPositiveDefinite {
            get {
                return ResourceManager.GetString("ArgumentMatrixSymmetricPositiveDefinite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Value must neither be infinite nor NaN. 的當地語系化字串。
        /// </summary>
        internal static string ArgumentNotInfinityNaN {
            get {
                return ResourceManager.GetString("ArgumentNotInfinityNaN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Value must not be negative (zero is ok). 的當地語系化字串。
        /// </summary>
        internal static string ArgumentNotNegative {
            get {
                return ResourceManager.GetString("ArgumentNotNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} is a null reference (Nothing in Visual Basic). 的當地語系化字串。
        /// </summary>
        internal static string ArgumentNull {
            get {
                return ResourceManager.GetString("ArgumentNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} must be greater than {1}. 的當地語系化字串。
        /// </summary>
        internal static string ArgumentOutOfRangeGreater {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} must be greater than or equal to {1}. 的當地語系化字串。
        /// </summary>
        internal static string ArgumentOutOfRangeGreaterEqual {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeGreaterEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The chosen parameter set is invalid (probably some value is out of range). 的當地語系化字串。
        /// </summary>
        internal static string ArgumentParameterSetInvalid {
            get {
                return ResourceManager.GetString("ArgumentParameterSetInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The given expression does not represent a complex number. 的當地語系化字串。
        /// </summary>
        internal static string ArgumentParseComplexNumber {
            get {
                return ResourceManager.GetString("ArgumentParseComplexNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Value must be positive (and not zero). 的當地語系化字串。
        /// </summary>
        internal static string ArgumentPositive {
            get {
                return ResourceManager.GetString("ArgumentPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Size must be a Power of Two. 的當地語系化字串。
        /// </summary>
        internal static string ArgumentPowerOfTwo {
            get {
                return ResourceManager.GetString("ArgumentPowerOfTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Size must be a Power of Two in every dimension. 的當地語系化字串。
        /// </summary>
        internal static string ArgumentPowerOfTwoEveryDimension {
            get {
                return ResourceManager.GetString("ArgumentPowerOfTwoEveryDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The range between {0} and {1} must be less than or equal to {2}. 的當地語系化字串。
        /// </summary>
        internal static string ArgumentRangeLessEqual {
            get {
                return ResourceManager.GetString("ArgumentRangeLessEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Array must have exactly one dimension (and not be null). 的當地語系化字串。
        /// </summary>
        internal static string ArgumentSingleDimensionArray {
            get {
                return ResourceManager.GetString("ArgumentSingleDimensionArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Value is too large. 的當地語系化字串。
        /// </summary>
        internal static string ArgumentTooLarge {
            get {
                return ResourceManager.GetString("ArgumentTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Value is too large for the current iteration limit. 的當地語系化字串。
        /// </summary>
        internal static string ArgumentTooLargeForIterationLimit {
            get {
                return ResourceManager.GetString("ArgumentTooLargeForIterationLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Type mismatch. 的當地語系化字串。
        /// </summary>
        internal static string ArgumentTypeMismatch {
            get {
                return ResourceManager.GetString("ArgumentTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Array length must be a multiple of {0}. 的當地語系化字串。
        /// </summary>
        internal static string ArgumentVectorLengthsMultipleOf {
            get {
                return ResourceManager.GetString("ArgumentVectorLengthsMultipleOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 All vectors must have the same dimensionality. 的當地語系化字串。
        /// </summary>
        internal static string ArgumentVectorsSameLengths {
            get {
                return ResourceManager.GetString("ArgumentVectorsSameLengths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The vector must have 3 dimensions. 的當地語系化字串。
        /// </summary>
        internal static string ArgumentVectorThreeDimensional {
            get {
                return ResourceManager.GetString("ArgumentVectorThreeDimensional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This feature is not implemented yet (but is planned). 的當地語系化字串。
        /// </summary>
        internal static string FeaturePlannedButNotImplementedYet {
            get {
                return ResourceManager.GetString("FeaturePlannedButNotImplementedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Invalid Left Boundary Condition. 的當地語系化字串。
        /// </summary>
        internal static string InvalidLeftBoundaryCondition {
            get {
                return ResourceManager.GetString("InvalidLeftBoundaryCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The operation could not be performed because the accumulator is empty. 的當地語系化字串。
        /// </summary>
        internal static string InvalidOperationAccumulatorEmpty {
            get {
                return ResourceManager.GetString("InvalidOperationAccumulatorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The operation could not be performed because the histogram is empty. 的當地語系化字串。
        /// </summary>
        internal static string InvalidOperationHistogramEmpty {
            get {
                return ResourceManager.GetString("InvalidOperationHistogramEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Not enough points in the distribution. 的當地語系化字串。
        /// </summary>
        internal static string InvalidOperationHistogramNotEnoughPoints {
            get {
                return ResourceManager.GetString("InvalidOperationHistogramNotEnoughPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No Samples Provided. Preparation Required. 的當地語系化字串。
        /// </summary>
        internal static string InvalidOperationNoSamplesProvided {
            get {
                return ResourceManager.GetString("InvalidOperationNoSamplesProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Invalid Right Boundary Condition. 的當地語系化字串。
        /// </summary>
        internal static string InvalidRightBoundaryCondition {
            get {
                return ResourceManager.GetString("InvalidRightBoundaryCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This special case is not supported yet (but is planned). 的當地語系化字串。
        /// </summary>
        internal static string SpecialCasePlannedButNotImplementedYet {
            get {
                return ResourceManager.GetString("SpecialCasePlannedButNotImplementedYet", resourceCulture);
            }
        }
    }
}
